/*
 * aggregate.ts - scans every module's database models, plus core areas under
 * src/core, and regenerates src/database/schema.ts (the aggregated Drizzle
 * schema used by the connection).
 *
 * Seeders are NOT aggregated here: the seed runner discovers them at runtime
 * (see src/core/database/seed.ts) and resolves FK ordering automatically.
 *
 * Run `deno task maker db:schema` (or `db:migrate`) after adding/removing a module or core model.
 */

import { fromFileUrl } from "@std/path";

const PROJECT_ROOT = fromFileUrl(new URL("../../../", import.meta.url));
const SRC_PATH = `${PROJECT_ROOT}src`;
const SCHEMA_PATH = `${SRC_PATH}/database/schema.ts`;

function walkTs(dir: string, out: string[]): void {
  try {
    for (const entry of Deno.readDirSync(dir)) {
      const full = `${dir}/${entry.name}`;
      if (entry.isDirectory) {
        walkTs(full, out);
      } else if (
        entry.isFile && (entry.name.endsWith(".ts") || entry.name.endsWith(".tsx"))
      ) {
        out.push(full);
      }
    }
  } catch {
    // path does not exist - skip
  }
}

// scan every module's database/models
const modelFiles: string[] = [];

for (const moduleDir of Deno.readDirSync(`${SRC_PATH}/modules`)) {
  if (!moduleDir.isDirectory) continue;
  walkTs(`${SRC_PATH}/modules/${moduleDir.name}/database/models`, modelFiles);
}

// scan every core area's database/models (e.g. src/core/queue/...)
for (const areaDir of Deno.readDirSync(`${SRC_PATH}/core`)) {
  if (!areaDir.isDirectory) continue;
  walkTs(`${SRC_PATH}/core/${areaDir.name}/database/models`, modelFiles);
}

modelFiles.sort();

// schema.ts lives at src/database/schema.ts, so both modules and core are
// referenced relative to src/ (../modules/... and ../core/...).
const modelExports = modelFiles
  .map((f) => {
    const rel = f.replace(SRC_PATH + "/", "");
    const ext = rel.endsWith(".tsx") ? ".tsx" : ".ts";
    const base = rel.slice(0, -ext.length);
    return `export * from "../${base}${ext}";`;
  })
  .join("\n");

const schemaContent = `/**
 * schema.ts - GENERATED by \`deno task maker db:schema\`. Do NOT edit by hand.
 * Aggregates every module + core database/models/*.ts into one Drizzle schema.
 */

${modelExports || "export {};"}
`;

await Deno.mkdir(`${SRC_PATH}/database`, { recursive: true });
await Deno.mkdir(`${SRC_PATH}/storage`, { recursive: true });
await Deno.writeTextFile(SCHEMA_PATH, schemaContent);
console.log(`[db:schema] wrote ${SCHEMA_PATH} (${modelFiles.length} model(s))`);
