#!/usr/bin/env -S deno run -A

/**
 * index.ts — the `./create` entry of `@niyam/deskapp`.
 *
 * `deno create jsr:@niyam/deskapp` downloads this package, runs the `./create`
 * entry, and scaffolds the starter project. When run with a project name it
 * creates a new folder; when run without one it scaffolds into the current
 * directory (the `deno create` flow).
 *
 * The scaffold content (template/) is consumed two ways depending on how this
 * script is loaded:
 *   - Locally (file:// import.meta.url, e.g. a repo checkout): it reads the
 *     template/ directory straight from disk.
 *   - Remotely (https://jsr.io/... import.meta.url, the real `deno create`
 *     case): the template files are fetched from the JSR registry CDN using
 *     the file list in template.manifest.json (generated by
 *     scripts/sync-template.mjs). `DENO create` runs this entry in a remote
 *     sandbox, so no local filesystem paths exist.
 *
 * After copying, the script materializes `.gitignore` from gitignore-stub,
 * writes `.env` from `.env.example`, renames the app, and prints next steps.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  renameSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type TemplateFiles = Map<string, Uint8Array>;

function walkTemplate(dir: string, rel: string, out: TemplateFiles): void {
  for (const entry of Deno.readDirSync(dir)) {
    const abs = join(dir, entry.name);
    const r = rel ? `${rel}/${entry.name}` : entry.name;
    if (entry.isDirectory) walkTemplate(abs, r, out);
    else out.set(r, Deno.readFileSync(abs));
  }
}

function isRemote(): boolean {
  return !import.meta.url.startsWith("file:");
}

function templateBaseUrl(): URL {
  const override = Deno.env.get("DESKAPP_CREATE_BASE");
  // When run from the registry, import.meta.url is
  //   https://jsr.io/@<scope>/<name>/<version>/src/index.ts
  // One level up is the versioned package root. JSR only serves package files
  // (template.manifest.json, template/**) at that versioned root — the
  // unversioned scope URL (`../../`) only serves the entry module and 404s for
  // everything else.
  const raw = override ?? new URL("../", import.meta.url).href;
  return raw.endsWith("/") ? new URL(raw) : new URL(raw + "/");
}

async function loadTemplateFiles(): Promise<TemplateFiles> {
  if (!isRemote()) {
    const templateDir = fileURLToPath(new URL("../template/", import.meta.url));
    const files: TemplateFiles = new Map();
    walkTemplate(templateDir, "", files);
    return files;
  }

  const base = templateBaseUrl();
  const manifestUrl = new URL("template.manifest.json", base);
  const res = await fetch(manifestUrl);
  if (!res.ok) {
    throw new Error(
      `Could not load template manifest from ${manifestUrl} (HTTP ${res.status}). ` +
        "Are you using an outdated published version?",
    );
  }
  const paths = await res.json() as string[];

  const templateDirUrl = new URL("template/", base);
  const files: TemplateFiles = new Map();
  for (const path of paths) {
    const url = new URL(path, templateDirUrl);
    const fileRes = await fetch(url);
    if (!fileRes.ok) {
      throw new Error(
        `Could not download template file ${path} from ${url} (HTTP ${fileRes.status}).`,
      );
    }
    files.set(path, new Uint8Array(await fileRes.arrayBuffer()));
  }
  return files;
}

const UI_SCRIPT_EXTENSIONS = new Set([".ts", ".tsx", ".js", ".jsx", ".mjs"]);

// deno publish rewrites import-map shorthand into fully-qualified specifiers
// (e.g. vue → npm:vue@^3.5.42). Deno consumers are fine with that, but Vite /
// Rolldown must see plain bare specifiers (resolved via node_modules + the
// scaffold's deno.json imports map). Frontend files live under src/ui/, so for
// those we undo the npm: prefix (and version) that publish added.
function stripNpmSpecifiers(text: string): string {
  return text.replace(
    /(from\s*["']|import\s*["']|declare\s+module\s*["'])npm:\/?([^"']+)/g,
    (_, prefix: string, spec: string) =>
      prefix + spec.replace(/^(@?[^@/]+(?:\/[^@/]+)?)@[^/]+/, "$1"),
  );
}

function transformTemplateFile(rel: string, bytes: Uint8Array): Uint8Array {
  if (!rel.startsWith("src/ui/")) return bytes;
  const dot = rel.lastIndexOf(".");
  const ext = dot === -1 ? "" : rel.slice(dot);
  if (!UI_SCRIPT_EXTENSIONS.has(ext)) return bytes;
  const text = new TextDecoder().decode(bytes);
  const out = stripNpmSpecifiers(text);
  return out === text ? bytes : new TextEncoder().encode(out);
}

function writeTemplateFiles(files: TemplateFiles, target: string): void {
  for (const [rel, bytes] of files) {
    const abs = join(target, ...rel.split("/"));
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, transformTemplateFile(rel, bytes));
  }
}

interface Args {
  name?: string;
  force?: boolean;
}

function parseArgs(argv: string[]): Args {
  const args: Args = {};
  for (const a of argv) {
    if (a === "--force" || a === "-f") args.force = true;
    else if (!a.startsWith("--")) args.name = a;
  }
  return args;
}

function isValidName(name: string): boolean {
  return /^[a-z0-9@][a-z0-9._-]*$/i.test(name);
}

function toPascal(name: string): string {
  return name.replace(/[-_.]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
    .replace(/\s+/g, "");
}

async function main(): Promise<void> {
  const { name, force } = parseArgs(Deno.args);
  const inPlace = !name;
  const projectName = inPlace ? basename(resolve(".")) : name!;

  if (!isValidName(projectName)) {
    console.error(`Error: "${projectName}" is not a valid project name.`);
    console.error(
      "Project names must use letters, digits, dashes, or underscores.",
    );
    console.error();
    console.error("Usage:");
    console.error("  deno create jsr:@niyam/deskapp            # run inside your new project folder");
    console.error("  deno run -A jsr:@niyam/deskapp/create <project-name> [--force]");
    Deno.exit(1);
  }

  const target = inPlace ? resolve(".") : resolve(projectName);

  if (inPlace) {
    if (Deno.readDirSync(target).next().value && !force) {
      console.error(
        `Error: the current directory is not empty. Run in an empty folder, or scaffold with a name:`,
      );
      console.error("  deno run -A jsr:@niyam/deskapp/create <project-name> [--force]");
      Deno.exit(1);
    }
  } else {
    if (existsSync(target)) {
      if (!force) {
        console.error(
          `Error: Directory "${projectName}" already exists. Pass --force to overwrite it.`,
        );
        Deno.exit(1);
      }
      rmSync(target, { recursive: true, force: true });
    }
    mkdirSync(target, { recursive: true });
  }

  let files: TemplateFiles;
  try {
    files = await loadTemplateFiles();
  } catch (err) {
    console.error("Error: could not load the deskapp template.");
    console.error(String(err instanceof Error ? err.message : err));
    Deno.exit(1);
  }

  writeTemplateFiles(files, target);

  const gitignoreStub = join(target, "gitignore-stub");
  if (files.has("gitignore-stub") && existsSync(gitignoreStub)) {
    renameSync(gitignoreStub, join(target, ".gitignore"));
  }

  const envPath = join(target, ".env");
  if (!existsSync(envPath)) {
    const examplePath = join(target, ".env.example");
    if (existsSync(examplePath)) {
      writeFileSync(envPath, readFileSync(examplePath, "utf-8"));
    }
  }

  const denoJsonPath = join(target, "deno.json");
  if (existsSync(denoJsonPath)) {
    const cfg = JSON.parse(readFileSync(denoJsonPath, "utf-8"));
    if (cfg?.desktop?.app?.name === "Deskapp") {
      cfg.desktop.app.name = toPascal(projectName);
    }
    writeFileSync(denoJsonPath, JSON.stringify(cfg, null, 2) + "\n");
  }

  console.log(inPlace
    ? `Done! Created deskapp project "${projectName}" in the current directory.`
    : `Done! Created "${projectName}" at ${target}`);
  console.log();
  if (!inPlace) console.log("  cd " + projectName);
  console.log("  deno install              # resolve deps (vite, sass, drizzle, ...)");
  console.log("  deno task dev             # codegen + build UI + open the desktop window");
  console.log("  deno run -A src/main.ts   # headless (no window, tray-only)");
  console.log();
  console.log("Tune your app: edit deno.json > desktop.app.name and deepLinks,");
  console.log("the icon files in src/icons/, and the frontend in src/ui/.");
}

await main();