// AUTO-GENERATED by `deno task maker bindings:gen`. Do not edit.
// Regenerates the controller list so packaged builds don't rely on scanning
// the (empty) filesystem at runtime.

import * as mod0 from "@/modules/app/controllers/demo.controller.ts";
import * as mod1 from "@/modules/app/controllers/deno.controller.ts";
import * as mod2 from "@/modules/app/controllers/net.controller.ts";
import * as mod3 from "@/modules/app/controllers/playwright.controller.ts";
import * as mod4 from "@/modules/app/controllers/storage.controller.ts";
import * as mod5 from "@/modules/app/controllers/window.controller.ts";

export interface GeneratedController {
  module: string;
  controller: string;
  mod: Record<string, unknown>;
}

export const GENERATED_CONTROLLERS: GeneratedController[] = [
  { module: "app", controller: "demo", mod: mod0 },
  { module: "app", controller: "deno", mod: mod1 },
  { module: "app", controller: "net", mod: mod2 },
  { module: "app", controller: "playwright", mod: mod3 },
  { module: "app", controller: "storage", mod: mod4 },
  { module: "app", controller: "window", mod: mod5 },
];
