import { fromFileUrl } from "@std/path";

const SRC_PATH = fromFileUrl(new URL("../..", import.meta.url));

type Entry = { module: string; controller: string; path: string };

function walkControllers(dir: string, out: string[]): void {
  try {
    for (const entry of Deno.readDirSync(dir)) {
      const full = `${dir}/${entry.name}`;
      if (entry.isDirectory) {
        walkControllers(full, out);
      } else if (entry.isFile && entry.name.endsWith(".controller.ts")) {
        out.push(full);
      }
    }
  } catch {
    // directory does not exist - skip
  }
}

function discoverControllerFiles(): string[] {
  const files: string[] = [];
  for (const moduleDir of Deno.readDirSync(`${SRC_PATH}/modules`)) {
    if (!moduleDir.isDirectory) continue;
    walkControllers(`${SRC_PATH}/modules/${moduleDir.name}/controllers`, files);
  }
  for (const areaDir of Deno.readDirSync(`${SRC_PATH}/core`)) {
    if (!areaDir.isDirectory) continue;
    walkControllers(`${SRC_PATH}/core/${areaDir.name}/controllers`, files);
  }
  return files.sort();
}

function namesOf(file: string): { module: string; controller: string } {
  const rel = file.replace(SRC_PATH + "/", "").replace(/\\/g, "/");
  const root = rel.startsWith("core/") ? "core" : "modules";
  const parts = rel.slice(root.length + 1).split("/");
  // modules/<module>/controllers/<name>.controller.ts
  return { module: parts[0], controller: parts[2].replace(/\.controller\.ts$/, "") };
}

const entries: Entry[] = discoverControllerFiles().map((file) => {
  const { module, controller } = namesOf(file);
  return { module, controller, path: file };
});

const specifierOf = (file: string): string => {
  const rel = file.replace(SRC_PATH + "/", "").replace(/\\/g, "/");
  return `@/${rel}`;
};

const imports = entries
  .map((e, i) => `import * as mod${i} from ${JSON.stringify(specifierOf(e.path))};`)
  .join("\n");

const array = entries
  .map(
    (e, i) =>
      `  { module: ${JSON.stringify(e.module)}, controller: ${JSON.stringify(e.controller)}, mod: mod${i} },`,
  )
  .join("\n");

const out = `// AUTO-GENERATED by \`deno task maker bindings:gen\`. Do not edit.
// Regenerates the controller list so packaged builds don't rely on scanning
// the (empty) filesystem at runtime.

${imports}

export interface GeneratedController {
  module: string;
  controller: string;
  mod: Record<string, unknown>;
}

export const GENERATED_CONTROLLERS: GeneratedController[] = [
${array}
];
`;

const outFile = new URL("./bindings.generated.ts", import.meta.url);
await Deno.writeTextFile(outFile, out);
console.log(`[bindings:gen] wrote ${fromFileUrl(outFile)} (${entries.length} controller(s))`);